# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-30 06:29
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('picture', models.FileField(blank=True, upload_to='pictures/')),
                ('gender', models.CharField(choices=[('F', 'Feminine'), ('M', 'Masculine')], max_length=1)),
                ('birthday', models.DateField(blank=True)),
                ('motto', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='PlayerBoard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField(default=0)),
                ('win_count', models.IntegerField(default=0)),
                ('lose_count', models.IntegerField(default=0)),
                ('player', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='player.Player')),
            ],
        ),
    ]
