# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-30 07:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_auto_20170930_0629'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='player_points',
        ),
        migrations.RemoveField(
            model_name='game',
            name='rival_points',
        ),
        migrations.AddField(
            model_name='score',
            name='game',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='games.Game'),
        ),
    ]
