# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-02 14:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_auto_20171002_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
